### ISSUE TITLE
PDF version

### ISSUE THREAD

**Issue by angea** [inforion/idapython-cheatsheet#1]
Hey there.
Awesome cheat sheets!
Could you also provide PDF versions so that we can print them at any resolution?

TIA,

Ange

**Comment by prusanov** [comment]
Hello!
Thank you for feedback! This is a really useful thing.
PDF version are now here: https://github.com/inforion/idapython-cheatsheet/releases/tag/pdf

**Comment by angea** [comment]
Thank you!!!
Just advertised them...
